## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Github: https://github.com/CloudGod93/pytorch-deep-learning

Help: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [41]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [42]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [43]:
scalar.ndim

0

In [44]:
# Get tensor back as Python init
scalar.item()

7

In [45]:
# Vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [46]:
vector.ndim

1

In [47]:
vector.shape

torch.Size([2])

In [48]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [49]:
MATRIX.ndim

2

In [50]:
MATRIX[1]

tensor([ 9, 10])

In [51]:
MATRIX.shape

torch.Size([2, 2])

In [52]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [53]:
TENSOR.ndim

3

In [54]:
TENSOR.shape

torch.Size([1, 3, 3])

In [55]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they sart with tensors full of random numbers and then adjust those random numbers to better represent the data/ 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [56]:
# Create a tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5940, 0.5961, 0.3045, 0.3464],
        [0.0081, 0.3015, 0.9296, 0.9818],
        [0.6903, 0.3330, 0.9647, 0.3340]])

In [57]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [58]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [60]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [61]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(start=0, end=101, step=10)
one_to_ten

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [62]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [63]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the tensor (e.g. float32, int32, int64)
                               device=None, # Where should the tensor be stored (e.g. 'cuda' or 'cpu')
                               requires_grad=False) # Does the tensor require a gradient?
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [64]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [65]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [66]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [67]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [68]:
# Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6948, 0.6758, 0.5993, 0.8428],
        [0.2532, 0.3280, 0.6896, 0.4303],
        [0.8934, 0.6736, 0.6002, 0.4106]])

In [69]:
# Find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [70]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [71]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [72]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [73]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [74]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learing:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices = https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [75]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [76]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [77]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [78]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


### One of the most common errors in deep learning: Shape Errors

In [ ]:
# # Shapes for matrix multiplication
# tensor_A = torch.tensor([[1, 2],
#                          [3, 4],
#                          [5, 6]])

# tensor_B = torch.tensor([[7, 8],
#                          [9, 10],
#                          [11, 12]])

# torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [80]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [81]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [82]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [83]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Shapes after transposing: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Shapes after transposing: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [84]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [86]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [87]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 dtype
torch.mean(x.type(torch.float32)), x.float().mean()

(tensor(45.), tensor(45.))

In [88]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [89]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [90]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor
x.argmin()

tensor(0)

In [91]:
x[0]

tensor(0)

In [92]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [93]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds a `1` dimension to a target tensor
* Permute - return a view of the input tensor with dimensions permuted (swapped) in a certain way

In [94]:
# Let's create a tensor
import torch # type: ignore
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [95]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [96]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [97]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [98]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([3, 9]))

In [99]:
# torch.squeeze() removes all single dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous tensor shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New tensor shape: torch.Size([9])


In [100]:
# torch.unsqueeze() adds a single dimension to a tensor at a specific index
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add a dimension to x_squeezed at index 0
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [101]:
# torch.permute - rearrange the dimensions of a tensor
x_original = torch.rand(size=(224, 224, 3)) # [224 height, 224 width, 3 color channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # [3 color channels, 224 height, 224 width]

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [102]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0] # note: the value at index [0, 0, 0] in x_original is now 728218

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)
indexing with PyTorch is similar to indexing with NumPy.

In [103]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [104]:
# lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
# lets index on the middle bracket
x[0, 0]

tensor([1, 2, 3])

In [106]:
# lets index on the most inner bracket (last dimension)
x[0, 0, 0]

tensor(1)

In [107]:
# You can also use ":" to select all values in a dimension
x[:, 0] 

tensor([[1, 2, 3]])

In [108]:
# Get all values of 0th and 1st dimensions but only inde 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [109]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [110]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [111]:
# index on x to return 9
print(x[0, 2, 2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library.
And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Data in PyTorch tensor, want in NumPy -> `torch.Tensor.numpy()`

In [112]:
# NumPy array to tensor
import torch # type: ignore
import numpy as np # type: ignore

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [113]:
# Change the value of array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [114]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take the randomness out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make better representations of the data -> again -> againg -> again... `

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [116]:
import torch # type: ignore

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Random tensor A:\n{random_tensor_A}\n")
print(f"Random tensor B:\n{random_tensor_B}\n")
print(f"Random tensor A + B:\n{random_tensor_A == random_tensor_B}\n")

Random tensor A:
tensor([[0.9005, 0.3862, 0.5886, 0.2746],
        [0.0557, 0.9134, 0.9312, 0.1740],
        [0.8980, 0.6184, 0.8290, 0.0506]])

Random tensor B:
tensor([[0.8786, 0.4071, 0.9562, 0.0212],
        [0.9976, 0.9990, 0.5298, 0.5781],
        [0.8059, 0.0209, 0.9216, 0.1410]])

Random tensor A + B:
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])



In [117]:
# Lets make some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Random tensor C:\n{random_tensor_C}\n")
print(f"Random tensor D:\n{random_tensor_D}\n")
print(f"Random tensor C + D:\n{random_tensor_C == random_tensor_D}\n")

Random tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Random tensor C + D:
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])



Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch on GPUs (and making faster connections)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options...
3. Use cloud computing - GCP, AWS, Azure. These services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [118]:
!nvidia-smi

Fri Mar 28 07:02:55 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   40C    P8              1W /   85W |     446MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [119]:
# Check for GPU access with PyTorch
import torch # type: ignore

torch.cuda.is_available() # returns True if GPU is available, else False

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#cuda-available

E.g. run on GPU if available, else run on CPU.

In [126]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda


In [127]:
# Count number of devices
torch.cuda.device_count() 


1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [131]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [132]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')


### 4. Moving tensors back to the CPU

In [135]:
# If tensor is on GPU, con't transform it to NumPy
# tensor_on_gpu.numpy()
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [136]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')