## 00. PyTorch Fundamentals

Resource notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

Github: https://github.com/CloudGod93/pytorch-deep-learning

Help: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [8]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [9]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [10]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python init
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7, 7])
print(vector)

tensor([7, 7])


In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[1]

tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [21]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they sart with tensors full of random numbers and then adjust those random numbers to better represent the data/ 

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html

In [25]:
# Create a tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7396, 0.5024, 0.5691, 0.0082],
        [0.6057, 0.8425, 0.3073, 0.4873],
        [0.6280, 0.5342, 0.2764, 0.0771]])

In [27]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [28]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange() instead
one_to_ten = torch.arange(start=0, end=101, step=10)
one_to_ten

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [44]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # What datatype is the tensor (e.g. float32, int32, int64)
                               device=None, # Where should the tensor be stored (e.g. 'cuda' or 'cpu')
                               requires_grad=False) # Does the tensor require a gradient?
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [46]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [48]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [50]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [51]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (Tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [52]:
# Create a tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4967, 0.1945, 0.4263, 0.6266],
        [0.6497, 0.1397, 0.0485, 0.7719],
        [0.8702, 0.0086, 0.1105, 0.5264]])

In [55]:
# Find out details about some tensor
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [59]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [60]:
# Subtract 10 from tensor
tensor - 10

tensor([-9, -8, -7])

In [61]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [62]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learing:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices = https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [65]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [66]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [67]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [68]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 0 ns


### One of the most common errors in deep learning: Shape Errors

In [94]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [95]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [96]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

In [97]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [101]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"Shapes after transposing: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
Shapes after transposing: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [103]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [105]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [106]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [110]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 dtype
torch.mean(x.type(torch.float32)), x.float().mean()

(tensor(45.), tensor(45.))

In [109]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))